#!/bin/bash
audio () {
  read -p "Please insert a valid URL for the video you're extracting the audio" URL
  youtube-dl --no-playlist -x $URL
  mv *.opus ~/videofetch-audios &> /dev/null
}


video () {
  confirm="y"
  deny="n"
  read -p "Is your video inside of a playlist?(y/n)" videop;
  if [[ "$videop" == "$confirm" ]]
  then
    read -p "now that i know it, please insert a VALID video URL" URL
    youtube-dl --no-playlist $URL
    mv *.mp4 *.webm *.mkv ~/videofetch-videos &> /dev/null
  elif [[ "$videop" == "$deny" ]]
  then
    read -p "now, paste ur video URL here" url2;
    youtube-dl $url2;
    mv *.mp4 *.webm *.mkv ~/videofetch-videos &> /dev/null
  else
    echo "ur kidding with my script, aren't u?";
  fi
}

playlist () {
 #this was actually my idea about replacing my spotify with a program that i made by myself
 read -p "Are you trying to download a music playlist?(y/n)" spotifyreplacer
  FSF="y"
  videokk="n"
  if [[ "$spotifyreplacer" == "$FSF" ]]
  then
     read -p "Insert a url of one music that is inside of the  playlist" musicfreedom
     youtube-dl --yes-playlist -x $musicfreedom
     mv *.opus ~/musicFSF &> /dev/null
  elif [["$spotifyreplacer" == "$videokk"]]
  then
     read -p "Insert a url of the video" $linkzin
     youtube-dl --yes-playlist $linkzin
     mv *.mp4 *.webm *.mkv ~/videofetch-playlists &> /dev/null
  else
    echo "do nothing...."; 
  fi
}

read -p "what do you want to download from the url you will insert?(audio/video/playlist)" youtube
case $youtube in
  audio)
  audio;
  ;;

  video)
  video;
  ;;

  playlist)
  playlist;
  ;;

  *)
  echo "please, don't troll this script....";
  ;;
esac

